# ╔════════════════════════════════════════════════════════════════════════════╗
# ║ This file is read only once per server start. Restart server when changed! ║
# ╚════════════════════════════════════════════════════════════════════════════╝

# Site settings
# ─────────────
baseurl: "/1819-crowdfunding-eldinhairic" # the subpath of your site, e.g. /blog
url: "https://gdmgent-1819-nmd2.github.io/1819-crowdfunding-eldinhairic/" 
# host   : 127.0.0.1
# port   : 4000

# Custom Site variables
# ─────────────────────
show-style-guide: true # Show style guide in footer.
title: Prepd

# Build settings
# ──────────────
defaults:
  -
    scope:
      path: "style-guide"
    values:
      layout: style-guide

exclude:
  - Gemfile
  - README.md

plugins:
# - jekyll-feed
# - jekyll-gist
# - jekyll-mentions
# - jekyll-paginate
# - jekyll-redirect-from
# - jekyll-seo-tag
# - jekyll-sitemap
  - jemoji

sass:
  style: nested
#  style: expanded
#  style: compact
#  style: compressed